# Universal Function - (Ufunc)

In [2]:
import numpy as np
np.random.seed(0)

In [7]:
#reciprocal of elements in array
def reciprocal(arr):
    result = np.empty(len(arr))
    for i in range(len(arr)) :
        result[i] = 1/(arr[i])
    return result

arr = np.random.randint(0,10,size =5)
reciprocal(arr)
%timeit -n 100000 reciprocal(arr)

5.21 µs ± 173 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
#for large array
big_array = np.random.randint(1, 100, size=1000000)
%timeit reciprocal(big_array)  #time are in 0.5s which is quite large

579 ms ± 7.03 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
#performing the operation on array itself would be applied to each element
%timeit -n 100000 new_result = (1/arr) 

4.2 µs ± 110 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [18]:
%timeit -n 1 new_big_array = (1/big_array)  #took times in ms(4ms) compare to previous iterations taking time in s(579ms)

4.79 ms ± 2.69 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
#unfunc are flexible and can also be applied to ndarray
secd = np.random.randint(10,size=(3,3))
secd

array([[7, 8, 2],
       [3, 3, 8],
       [3, 2, 5]])

In [22]:
2 ** secd

array([[128, 256,   4],
       [  8,   8, 256],
       [  8,   4,  32]], dtype=int32)

In [28]:
#numpy ufunc 
#arithmetic function
x = np.random.randint(10,size = 10)
x

array([1, 0, 1, 8, 4, 9, 5, 7, 7, 0])

In [37]:
print("x+10 :" , np.add(x,10))
print("-x :" , -x)
print("x^2 :" , x ** 2)
print("x%3 :" , x%3)
print("x//2 :",x//2)

x+10 : [11 10 11 18 14 19 15 17 17 10]
-x : [-1  0 -1 -8 -4 -9 -5 -7 -7  0]
x^2 : [ 1  0  1 64 16 81 25 49 49  0]
x%3 : [1 0 1 2 1 0 2 1 1 0]
x//2 : [0 0 0 4 2 4 2 3 3 0]


In [38]:
x = np.array([-1,3,-2,5,8,-10])
np.absolute(x)

array([ 1,  3,  2,  5,  8, 10])

In [39]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.absolute(x)

array([5., 5., 2., 1.])

In [41]:
#Trigonometric functions
theta = np.linspace(0,np.pi,4)
print("theta(Q) : ",theta)
print("sinQ : " , np.sin(theta))

theta(Q) :  [0.         1.04719755 2.0943951  3.14159265]
sinQ :  [0.00000000e+00 8.66025404e-01 8.66025404e-01 1.22464680e-16]


In [46]:
#inverse trigonometric function
x = [0,1,-1]
print("sin_inv(Q) : ", np.arcsin(x))

sin_inv(Q) :  [ 0.          1.57079633 -1.57079633]


In [50]:
#exponential and logarithmic function of array
x=[1,2,3,10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("natural log(x) =", np.log10(x))
print("e^x :" , np.exp(x))

x = [1, 2, 3, 10]
ln(x) = [0.         0.69314718 1.09861229 2.30258509]
log2(x) = [0.         1.         1.5849625  3.32192809]
natural log(x) = [0.         0.30103    0.47712125 1.        ]
e^x : [2.71828183e+00 7.38905610e+00 2.00855369e+01 2.20264658e+04]


In [51]:
#high precicision value
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))   

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [52]:
#specify the array where the result of the calculation will be stored , rather than creating a temporary array to save memory
x = np.arange(10)
y = np.empty(10)
np.multiply(2,x,out=y) #compute result direct ly in memory to save space

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [60]:
y = np.zeros(10)
np.power(2, x, out=y[::])
print(y)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


# Aggregates

In [64]:
#reduce ->reduce an array by repeatedly applying the operation it's element until a single result remains
x = np.arange(1,10)
print("x: ",x)
print("Addition of x using reduce : " , np.add.reduce(x))
print("multiplication of x using reduce : " , np.multiply.reduce(x))

x:  [1 2 3 4 5 6 7 8 9]
Addition of x using reduce :  45
multiplication of x using reduce :  362880


In [65]:
np.add.accumulate(x) #store immidiate result after each computation

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [77]:
#outer
x = np.arange(1, 6)
np.multiply.outer(x,x[::-1])

array([[ 5,  4,  3,  2,  1],
       [10,  8,  6,  4,  2],
       [15, 12,  9,  6,  3],
       [20, 16, 12,  8,  4],
       [25, 20, 15, 10,  5]])

In [84]:
#time-difference between normal functions and numpy aggregate function while using numpy array
L = np.random.random(10000)
%timeit sum(L)
%timeit np.sum(L)

1.83 ms ± 43.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
12.2 µs ± 48.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [89]:
%timeit -n 10 np.min(L) , np.max(L)

30.3 µs ± 8.95 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [88]:
%timeit -n 10 min(L) , max(L)

2.42 ms ± 65.8 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [93]:
#multi dimensional aggregate
L = np.random.random((3,3))
L

array([[0.67746641, 0.57598592, 0.62842532],
       [0.46888543, 0.26721863, 0.07300732],
       [0.56155238, 0.53466223, 0.43597443]])

In [95]:
sum(L) , np.sum(L) #np.sum is aware of multidimensional array

(array([1.70790422, 1.37786678, 1.13740707]), 4.223178067105673)

In [97]:
np.sum(L,axis=1) , np.sum(L,axis=0) #axis=0 => taking rows , axis=1 => taking column

(array([1.88187765, 0.80911138, 1.53218904]),
 array([1.70790422, 1.37786678, 1.13740707]))

In [101]:
#nansafe aggregate ignores the missing value while computation