In [1]:
import numpy as np 
np.__version__

'1.22.2'

In [2]:
np?

In [3]:
l1 = list(range(10))
print(l1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
type(l1[0])

int

In [5]:
l2 = [str(x) for x in l1]
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
type(l2[0])

str

In [7]:
l3 = [True, "2", 3.0, 4 , [1,2,False]]
[type(x) for x in l3]

[bool, str, float, int, list]

In [8]:
import array
a = array.array('i',l1)# 'i' here is code type indicating contents are integer
b = array.array('f',l1)
a,b

(array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]))

In [9]:
type(a)

array.array

# numpy array

In [10]:
s = np.array([1,2,3,4,5])
s #same elements unlike list

array([1, 2, 3, 4, 5])

In [11]:
type(s)

numpy.ndarray

In [12]:
np.array([3.14,4,-4,0.01], dtype = 'float32' ) #upcast the integer to float + explicitly set datatype

array([ 3.14,  4.  , -4.  ,  0.01], dtype=float32)

In [13]:
type(np.array([3.14,4,-4,0.01], dtype = float ) )

numpy.ndarray

In [14]:
np.array([range(i,i+10,2) for i in [2,4,6]])
#initializing a multidimensional array (explicitly)
#The inner lists are treated as rows of the resulting two-dimensional array.

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [15]:
# Create a length-10 integer array filled with zeros
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3,5) , dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
# Create a 3x5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
# Create an array filled with a linear sequence
 # Starting at 0, ending at 20, stepping by 2
 # (this is similar to the built-in range() function)

np.arange(0,20,2) #(start , end , increment)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,15 , 4)

array([ 0.,  5., 10., 15.])

In [20]:
# Create a 3x3 array of uniformly distributed
 # random values between 0 and 1

np.random.random((3,3))

array([[0.42433411, 0.59947405, 0.45704702],
       [0.09146314, 0.47590069, 0.23237864],
       [0.43121726, 0.46416669, 0.92138081]])

In [21]:
# Create a 3x3 array of normally distributed random values
 # with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-2.24579572e+00, -1.49898707e+00, -5.41655202e-01],
       [-4.06433661e-01, -3.15601311e-04, -7.28571641e-01],
       [-1.13779694e+00, -1.98039623e+00, -9.26432372e-02]])

In [22]:
np.random.normal(0, 10, (3, 3))

array([[ -5.78931377,   9.09654138, -10.80948184],
       [  6.96425379,   3.82973218, -17.78344977],
       [ -6.51426243, -20.32717827,  -9.2607767 ]])

In [23]:
# Create a 3x3 array of random integers in the interval [0, 10]
np.random.randint(0,9,(3,3))

array([[7, 7, 8],
       [5, 2, 2],
       [0, 1, 1]])

In [24]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.empty(3)

array([1., 1., 1.])

# Array Attributes 

In [26]:
#Array attributes
np.random.seed(0)  #to produce same random number

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [27]:
print("x1 ndim: ", x1.ndim , "\tx2 ndim: ", x2.ndim , "\tx3 ndim: ", x3.ndim)
print("x1 shape:", x1.shape , "\tx2 shape:", x2.shape , "\tx3 shape:", x3.shape)
print("x1 size: ", x1.size , "\tx2 size: ", x2.size ,"\tx3 size: ", x3.size)

x1 ndim:  1 	x2 ndim:  2 	x3 ndim:  3
x1 shape: (6,) 	x2 shape: (3, 4) 	x3 shape: (3, 4, 5)
x1 size:  6 	x2 size:  12 	x3 size:  60


In [28]:
print(x3.dtype)

int32


In [29]:
print("itemsize" , x3.itemsize , "bytes") #size of each array elements
print("nbytes" , x3.nbytes , "bytes") #total size of array

itemsize 4 bytes
nbytes 240 bytes


In [30]:
#Array Indexing
#Use previous array and judge the placement to value at particular index
x1

array([5, 0, 3, 3, 7, 9])

In [31]:
x1[5]

9

In [32]:
x2 #two index would be used

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [33]:
x2[1,3]

8

In [34]:
#Array Slicing
#[Start:Stop:Increment/Step]

x1[2:5]

array([3, 3, 7])

In [35]:
x1[::2] #start to end with 2 increment

array([5, 3, 7])

In [36]:
x1[::-1] #reverse order

array([9, 7, 3, 3, 0, 5])

In [37]:
x2[::2]

array([[3, 5, 2, 4],
       [1, 6, 7, 7]])

In [38]:
x2[:,0] #0th column

array([3, 7, 1])

In [39]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [40]:
new_x2 = x2[:2,:2] # 2-rows , 2-column
print(new_x2) 

[[3 5]
 [7 6]]


In [41]:
new_x2[0,0] = 6 
new_x2[0,1] = 4
print(new_x2)  #values changed in new array 

[[6 4]
 [7 6]]


In [42]:
#changes in new array will reflect in original
x2

array([[6, 4, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [43]:
copy_x2 = x2[:2,:2].copy()
copy_x2

array([[6, 4],
       [7, 6]])

In [44]:
copy_x2[0,0] = 1000
print("x2 :\n" , x2)
print("copied version :\n",copy_x2)#changes not reflected in original

x2 :
 [[6 4 2 4]
 [7 6 8 8]
 [1 6 7 7]]
copied version :
 [[1000    4]
 [   7    6]]


In [45]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
new_x = x.reshape((3,3))
new_x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
x[:,np.newaxis] #1x9

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [48]:
a = np.arange(9)
b = np.arange(20,0,-2)

In [49]:
np.concatenate([a,b])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 20, 18, 16, 14, 12, 10,  8,  6,
        4,  2])

In [50]:
c = np.arange(30,51,5)
np.concatenate([a,b,c])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 20, 18, 16, 14, 12, 10,  8,  6,
        4,  2, 30, 35, 40, 45, 50])

In [51]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [54]:
d=np.array([99,88,77])
np.vstack([grid,d]) #vertically stacking the arrays

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 88, 77]])

In [55]:
e = np.array([[100],[200]]) #2x2 matrix of required size is need for hstack
np.hstack([grid,e]) #horizontally stacking the arrays 

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200]])

In [56]:
rd3 = np.arange(0,27).reshape((3,3,3))                     #for 3x3x3 matrix
f = np.array([[100,200,300],[300,400,500],[600,700,800]])  #3x3 matrix is needed for dstack
rd3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
np.dstack([rd3,f])

array([[[  0,   1,   2, 100],
        [  3,   4,   5, 200],
        [  6,   7,   8, 300]],

       [[  9,  10,  11, 300],
        [ 12,  13,  14, 400],
        [ 15,  16,  17, 500]],

       [[ 18,  19,  20, 600],
        [ 21,  22,  23, 700],
        [ 24,  25,  26, 800]]])

In [58]:
#Splitting of array
#Opposite of concatenation
grid = np.arange(0,14)

In [59]:
s1,s2,s3 = np.split(grid,[5,10])
print(s1,s2,s3)

[0 1 2 3 4] [5 6 7 8 9] [10 11 12 13]


In [60]:
grid = np.arange(0,16).reshape([4,4])
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
upper , lower = np.vsplit(grid,[2]) #0th,1st row --- upper , 2nd,3rd row ----lower
print("upper :\n" , upper , "\nlower :\n" , lower)

upper :
 [[0 1 2 3]
 [4 5 6 7]] 
lower :
 [[ 8  9 10 11]
 [12 13 14 15]]


In [62]:
right , left = np.hsplit(grid,[3])  #0th,1st,2nd column --- right , 2nd,3rd column ----left
print("right :\n" , right , "\nleft :\n" , left)

right :
 [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]] 
left :
 [[ 3]
 [ 7]
 [11]
 [15]]


In [63]:
rd3 = np.arange(0,27).reshape((3,3,3))  #for 3x3x3 matrix
np.dsplit(rd3,[2,2])

[array([[[ 0,  1],
         [ 3,  4],
         [ 6,  7]],
 
        [[ 9, 10],
         [12, 13],
         [15, 16]],
 
        [[18, 19],
         [21, 22],
         [24, 25]]]),
 array([], shape=(3, 3, 0), dtype=int32),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]